import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { fal } from '@fal-ai/client';
import dotenv from 'dotenv';

// Load environment variables from .env file
dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;

// Configure FAL with server-side key
const FAL_KEY = process.env.FAL_KEY;
if (FAL_KEY) {
  fal.config({
    credentials: FAL_KEY,
  });
} else {
  console.warn('⚠️  WARNING: FAL_KEY environment variable is not set!');
}

app.use(express.json({ limit: '50mb' }));

// Increase timeout for long-running AI operations
app.use((req, res, next) => {
  req.setTimeout(300000); // 5 minutes
  res.setTimeout(300000); // 5 minutes
  next();
});

// API endpoint to proxy FAL requests
app.post('/api/generate', async (req, res) => {
  try {
    console.log('📸 Received generation request');
    
    // Accept locations array and samples per location
    const { imageFile, locations, samplesPerLocation = 2 } = req.body;
    
    // Backwards compatibility for single location
    const locationList = Array.isArray(locations) ? locations : (req.body.location ? [req.body.location] : []);

    if (!imageFile || locationList.length === 0) {
      console.error('❌ Missing imageFile or locations');
      return res.status(400).json({ error: 'Missing imageFile or locations' });
    }

    if (!FAL_KEY) {
      console.error('❌ FAL_KEY not configured');
      return res.status(500).json({ error: 'Server not configured. Please set FAL_KEY environment variable.' });
    }

    console.log(`📍 Locations: ${locationList.join(', ')}`);
    console.log(`🔢 Samples per location: ${samplesPerLocation}`);
    
    // Convert data URL to blob
    const response = await fetch(imageFile);
    const blob = await response.blob();
    
    console.log('☁️  Uploading image to FAL...');
    const imageUrl = await fal.storage.upload(blob);
    console.log(`✅ Image uploaded: ${imageUrl}`);

    // Generate requests for ALL locations
    const promises = [];

    // Define prompt variations
    const promptTemplates = [
      `Selfie of the person in the reference image at {location}, happy, highly detailed, 4k, realistic lighting`,
      `A wide shot of the person from the reference image standing in {location}, cinematic composition, golden hour`,
      `Portrait of the person in the reference image at {location}, professional photography, natural lighting, 8k`,
      `The person from the reference image exploring {location}, candid shot, vibrant colors, photorealistic`
    ];

    for (const loc of locationList) {
      console.log(`🎨 Queueing ${samplesPerLocation} generation(s) for: ${loc}`);
      
      // Queue the requested number of samples for this location
      for (let i = 0; i < samplesPerLocation; i++) {
        const prompt = promptTemplates[i % promptTemplates.length].replace('{location}', loc);
        
        promises.push(
          fal.subscribe("fal-ai/nano-banana-pro/edit", {
            input: {
              prompt,
              image_urls: [imageUrl],
              num_images: 1,
              resolution: "1K"
            },
            logs: true,
          }).then(res => ({ res, loc, type: `sample_${i + 1}` }))
        );
      }
    }

    console.log(`🚀 Processing ${promises.length} total generations...`);
    const responses = await Promise.all(promises);
    
    const results = [];
    for (const { res, loc } of responses) {
      console.log(`📦 Response for ${loc}:`, res.data ? 'Has data' : 'No data');
      if (res.data.images?.[0]?.url) {
        console.log(`✅ Image URL for ${loc}:`, res.data.images[0].url);
        results.push({
          url: res.data.images[0].url,
          location: loc
        });
      } else {
        console.warn(`⚠️  No image generated for ${loc}`);
      }
    }

    console.log(`✨ Generated ${results.length} images successfully out of ${promises.length} requests`);
    
    if (results.length === 0) {
      throw new Error('No images were generated by the AI model');
    }
    
    res.json({ images: results });
    
  } catch (error) {
    console.error('❌ Generation error:', error);
    res.status(500).json({ 
      error: 'Failed to generate images', 
      details: error instanceof Error ? error.message : 'Unknown error'
    });
  }
});

// Serve static files and handle SPA routing
app.use(express.static(path.join(__dirname, 'dist')));
app.use((req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`🚀 Server running on http://localhost:${PORT}`);
  if (!FAL_KEY) {
    console.log('⚠️  Remember to set FAL_KEY environment variable!');
  }
});

